### ISSUE TITLE
Context for error message

### ISSUE THREAD

**Issue by nplrkn** [gabhijit/hampi#13]
Hello again @gabhijit.  Wanted to run an idea past you before diving in.

It would be helpful if error messages provided context saying how far we had got through the encode / decode when we hit the problem.  To achieve this I am thinking that the context could be added as the error is propagated.

Imagine that the starting point is this (which might be macro derived):
```
impl AperCodec for Tac {
    fn decode(data: &mut AperCodecData) -> Result<Self::Output, AperCodecError> {
        Ok(Self(aper::decode::decode_octetstring(data, Some(3), Some(3), false)?))
    }
}
```
Then, to add the error context, you would wrap that in a block with a map_err at the end, like this...
```
impl AperCodec for Tac {
    fn decode(data: &mut AperCodecData) -> Result<Self::Output, AperCodecError> {
        {
            Ok(Self(aper::decode::decode_octetstring(data, Some(3), Some(3), false)?))
        }.map_err(|e: AperCodecError| e.add_context("Tac")) 
    }
}
```
In which case we would need:
```
impl Error {
    pub fn add_context(self, context_elem: &str) -> Self {...}
}
```

Do you think this would fly?  As usual, I would be happy to send a PR for `codecs` but (because I am working with a different upper layer) would prefer not to include the work to `codecs_derive` to make use of it.

**Comment by gabhijit** [comment]
I think the idea is good - but example code is a bit complicated something like following won't work? 

```rust
impl AperCodec for Tac {
    fn decode(data: &mut AperCodecData) -> Result<Self::Output, AperCodecError> {
            Ok(Self(aper::decode::decode_octetstring(data, Some(3), Some(3), false)).map_err(|e: AperCodecError| e.add_context("Tac")?)) 
    }
}
```

**Comment by nplrkn** [comment]
Yes, definitely that would work.  I didn't explain very well - the construct I gave above was more tailored for the case where there is a big chain of encode or decode calls, and would be a way to avoid repeating the same `map_err` for each one.

In the other thread you mentioned using `AperCodecData` to store the context.  I did wonder about that, but it seemed to me a bit simpler and more performant if we build up the context only as we unwind the stack after an error.  Re panicking, while that might be an alternative way of providing debugging info when encoding, we obviously don't want to panic on decode.

If you're happy with where this is going, I'll aim to get a PR over to you for this one in the next day or so.

**Comment by gabhijit** [comment]
> In the other thread you mentioned using AperCodecData to store the context. I did wonder about that, but it seemed to me a bit simpler and more performant if we build up the context only as we unwind the stack after an error.

Yes that is true, but I am not sure how one would have the context about the original ASN data type that was failing. But likely I am missing something and I don't have the full context about what you have in mind! :-) 

> If you're happy with where this is going, I'll aim to get a PR over to you for this one in the next day or so.

Yes sure! I think we have made a lot of progress in the encode functionality and I am really happy that someone else  is looking at the code. But let's look at it once we close #11 which, I believe we are pretty close to finishing.

**Comment by nplrkn** [comment]
Oops... my example above has the fatal flaw that ? doesn't jump out of the block, it jumps out of the function, so you don't hit the final map_err().

**Comment by nplrkn** [comment]
New example.  This is the only way I can now think of to have a single map_err().
```
impl Tac {
    fn decode(data: &mut AperCodecData) -> Result<Self, AperCodecError> {
        Ok(Self(aper::decode::decode_octetstring(data, Some(3), Some(3), false)?))
    }
}

impl AperCodec for Tac {
    fn decode(data: &mut AperCodecData) -> Result<Self::Output, AperCodecError> {
        Tac::decode(data).map_err(|e: AperCodecError| e.add_context("Tac"))
    }
}
```

**Comment by gabhijit** [comment]
PR is merged. Closing this issue.
