### ISSUE TITLE
`encode_integer()` input limit

### ISSUE THREAD

**Issue by huixue** [gabhijit/hampi#26]
Here's the encode_integer() signature: 

```
pub fn encode_integer(
    data: &mut AperCodecData,
    lb: Option<i128>,
    ub: Option<i128>,
    is_extensible: bool,
    value: i128,
    extended: bool,
) -> Result<(), AperCodecError> {...}

```

input value is i128.

What if the to-be-encoded integer is beyond i128 range?

**Comment by huixue** [comment]
In asn1c, such a case is encoded in unconstrained case, where, I believe, is also when no constrains are given:

```
 for(buf = st->buf, end = st->buf + st->size; buf < end;) {
        int need_eom = 0;
        ssize_t mayEncode = aper_put_length(po, -1, end - buf, &need_eom);
        if(mayEncode < 0)
            ASN__ENCODE_FAILED;
        if(per_put_many_bits(po, buf, 8 * mayEncode))
            ASN__ENCODE_FAILED;
        buf += mayEncode;
        if(need_eom && aper_put_length(po, -1, 0, 0)) ASN__ENCODE_FAILED;
    }
```
The code snippet has its context in prev issue:

#20

**Comment by gabhijit** [comment]
> input value is i128.
> 
> What if the to-be-encoded integer is beyond i128 range?

I believe, we should document somewhere explicitly but right now there is no support for integers bigger than `i128`. As discussed, the original focus is in the implementation of 3GPP protocols and so far I have not come across a case where this support may be insufficient. So for now it will be a limitation. Once we add proper documentation for this case, I believe this issue can be closed?

**Comment by huixue** [comment]
I wouldn't mind "closing" this issue, given that we know it's a documented limitation. Such a limitation would, sometimes, become a defect, for a user not aware.

Also, we shall begin thinking about some "checkers" for limitations?

**Comment by gabhijit** [comment]
@huixue : That's why I recommended - Let's have it properly documented somewhere and then close it. I will document it in the `codecs` code documentation and also somewhere in the compiler code.

**Comment by gabhijit** [comment]
This is documented in #33 and we can close this now.
