### ISSUE TITLE
Supporting `UPER` encoding in the `codecs` trait. 

### ISSUE THREAD

**Issue by gabhijit** [gabhijit/hampi#32]
As the support for PER encoding is in place (Aligned PER), support for Unaligned PER can be added with little effort. 

A test case for decoding and encoding of at-least one of the supported protocols (like `NR-RRC`) should be included once this support is in place.

Ideally this can be integrated with the compiler trait after #29 is added - which takes the codecs as a command line switch, thus we do not unnecessarily generate codecs that are not required.

**Comment by huixue** [comment]
I guess APER is still pending? Because codecs/src/aper/mod.rs still has encode( ) as todo!( ) ...

**Comment by gabhijit** [comment]
That is a default implementation which basically says - if it is not implemented for a specific `struct` use this implementation.I believe we will keep the implementation as it is - may be a good idea to document that. This way it's easier to catch if we miss the implementation for some `struct`.

**Comment by ljbade** [comment]
I will vote for this feature as UPER is used for both SUPL and LPP.

I look forward to being able to use this compiler instead of asn1c as this Rust compiler is much easier to work with then trying to integrate asn1c with Rust.

**Comment by gabhijit** [comment]
@ljbade: Can you point me to a few traces where I can take a look at some actual `UPER` encoded data that I can use for testing

**Comment by ljbade** [comment]
@gabhijit I have been testing SUPL using the Google server supl.google.com, two SUPL clients that work are https://github.com/google/supl-client and https://github.com/Ericsson/SUPL-3GPP-LPP-client

Otherwise when I have some time I can also grab some traces from the Google server using an asn1c based client I have been working on.

**Comment by gabhijit** [comment]
@ljbade : Thanks will take a look at it.

**Comment by gabhijit** [comment]
#56 fixes this.

A basic working support for UPER encoder is present. It is available with crate version `0.5.0` or can be directly used from the master branch. 
Note: This is a very early support and needs lot more testing.

**Comment by ljbade** [comment]
Awesome! I will test this with my SUPL client/server.
