### ISSUE TITLE
Add support for serde Serialize, Deserialize

### ISSUE THREAD

**Issue by huixue** [gabhijit/hampi#36]
In generated rust, such as ngap.rs, add Serialize, Deserialize for serde use
e.g.
```
#[derive(Debug, AperCodec)]
#[asn(type = "SEQUENCE", extensible = true)]
pub struct UEContextReleaseRequest {
    pub protocol_i_es: UEContextReleaseRequestProtocolIEs,
}
```
would be 
```
#[derive(Debug, AperCodec, Serialize, Deserialize)]
#[asn(type = "SEQUENCE", extensible = true)]
pub struct UEContextReleaseRequest {
    pub protocol_i_es: UEContextReleaseRequestProtocolIEs,
}
```

essentially, do we have a way for controlling what to "derive", in codegen?

The reason is, generated rust would very likely to be part of data structure defs, which better be able to use serde.

**Comment by huixue** [comment]
after digging a bit, seems generator code such as 
```
asn-compiler/src/generator/asn/types/base/integer.rs
```
is dealing with this
```
        let struct_tokens = quote! {
            #[derive(Debug, AperCodec)]
            #[asn(#ty_tokens)]
            pub struct #struct_name(pub #inner_type);
        };
```
would it be "wise" to just hard code stuff like ```#[derive(Debug, AperCodec, Serialize, Deserialize)]``` in for now?

**Comment by huixue** [comment]
update:
I just string replace ```#[derive(Debug, AperCodec)]``` to  ```#[derive(Debug, AperCodec, Serialize, Deserialize)]```
in the resulting ngap.rs, and with bitvec 1.0 feature "serde" enabled, it works with serde.

Now it's a question whether my previous suggestion in generator change will work, and do it once for good (configurable of enabling serde would be even better).

**Comment by gabhijit** [comment]
Sorry, somehow I missed this, I don't remember how. Is there really a case for `serde` serialize/deserialize? I am not entirely sure, but then may be there is some use-case that I have not thought about fully. 

I believe once we have support for the CLI switches, we can have this kind of 'opt ins' in the codegen part. 

Makes sense?

**Comment by huixue** [comment]
For example, when we have data structures in ngap.rs, and we want to serialize them into config files and deserialize them into data structures at runtime, such feature would be very helpful.

**Comment by gabhijit** [comment]
#42 supports this now. Right now it is only available from `git` after adding examples for how to write `build.rs` etc, I am going to make a new release, but this can be used from the git now. 
Note: The CLI is changed now properly so please refer the usage of the CLI

**Comment by gabhijit** [comment]
#44 adds the `build.rs` support and better documentation
