### ISSUE TITLE
Parse EXPORTS

### ISSUE THREAD

**Issue by ljbade** [gabhijit/hampi#46]
The SUPL specification uses the `EXPORTS` section. Currently the compiler fails with an unexpected token error because of this.

The `asn1c` documentation indicates they just parse but ignore the EXPORTS list.

I quickly modified the compiler to do that and it seems to do the job as it no longer fails to compile the file.

An example of the SUPL ASN file is available at https://github.com/boundary/wireshark/blob/master/asn1/ulp/SUPL.asn#L16

**Comment by gabhijit** [comment]
@ljbade : Thanks for reporting this. Can you create a PR for this?

**Comment by gabhijit** [comment]
Fix for this is available in #53 which is merged in master.

**Comment by gabhijit** [comment]
Fix for this is available in version v0.4.1

**Comment by ljbade** [comment]
Sorry for the slow reply, only just had time to take another look. Thanks for fixing this!
