### ISSUE TITLE
Parse SEQUENCE SIZE ( ... ) OF ...

### ISSUE THREAD

**Issue by ljbade** [gabhijit/hampi#47]
The SUPL specification uses the following syntax a few times:
`SEQUENCE SIZE (1.. 1024) OF ReportData`

Specifically the `SIZE ( ... )` part is not enclosed in additional braces.

The `asn1c` compiler is able to parse this fine, but the compiler here fails to parse it.

I wasn't able to figure out how to modify the parser code so I just modified the file to add the extra braces like:
`SEQUENCE (SIZE (1.. 1024)) OF ReportData`
and I was able to compile the file.

An example SUPL ASN file is at https://github.com/boundary/wireshark/blob/master/asn1/ulp/SUPL.asn#L645

**Comment by gabhijit** [comment]
Fix for this was added by #50. This PR is merged. @ljbade Can you please test if this works and close the issue?

**Comment by ljbade** [comment]
Sorry for the slow reply, only just had time to take another look. Thanks for fixing this!
