### ISSUE TITLE
Unimplemented builtin type causes infinite loop in compiler

### ISSUE THREAD

**Issue by ljbade** [gabhijit/hampi#48]
Encountered this issue while trying to compile https://github.com/boundary/wireshark/blob/master/asn1/ulp/SUPL.asn#L671

The compiler gets stuck in an infinite loop in `parse_choice_type` if the type is not recognised as a built in type in `parse_type`.

The compiler should error if this occurs.

I will try adding `UTCTime` to `BASE_TYPES` to try and finish compiling the file.

However this will happen again for any other of the unsupported built in types, so the infinite loop issue will need fixing.

**Comment by gabhijit** [comment]
Fix for this is available in version 0.4.1

**Comment by ljbade** [comment]
Sorry for the slow reply, only just had time to take another look. Thanks for fixing this!
