### ISSUE TITLE
How to call hampi-rs-asn1c?

### ISSUE THREAD

**Issue by xpromache** [gabhijit/hampi#64]
If I understand correctly, the hampi-rs-asn1c binary is supposed to generate some Rust sourcecode from asn specifications.

However I don't manage to run that binary. When I try this:
target/debug/hampi-rs-asn1c --module abc --codec uper  examples/specs/example/example.asn

I get this:

>  error: Found argument 'examples/specs/example/example.asn' which wasn't expected, or isn't valid in this context

Can you please provide some examples?

**Comment by xpromache** [comment]
hmm, I found I have to pass a -- before the filename:
target/debug/hampi-rs-asn1c --module abc --codec uper -- examples/specs/example/example.asn

I did try that earlier with one of my asn files but the command was never ending so I thought the "--" means reading standard input. I see now it is just hanging with 100% CPU consumption but I will open another issue for that.

**Comment by gabhijit** [comment]
@xpromache : The way to call this is as follows -  

```
target/debug/hampi-rs-asn1c --module abc --codec uper -- examples/specs/example/example.asn
```
Note: the path to asn file after `--` Right now this is treated as `last`, I believe this is a bit kludgy - will remove that .
