### ISSUE TITLE
codecs_derive/src/aper/mod.rs needs generate_encode()

### ISSUE THREAD

**Issue by huixue** [gabhijit/hampi#9]
Please add generate_encode()

**Comment by gabhijit** [comment]
Right now, there is some `generate_encode` functionality, but this is clearly work in progress. For example there is `encode` function generated inside `codecs_derive/src/aper/boolean.rs` and some other functions. This is not complete yet, but we are making a slow progress. 

Likely, `generate_decode` function will be renamed to `generate_codec` once we have it supported for all the types. It is kept as `generate_decode` (the name is bad agreed!)
