### ISSUE TITLE
NAS-5G

### ISSUE THREAD

**Issue by linouxis9** [gabhijit/hampi#95]
Hi!

Is it possible to use hampi to generate ASN.1 specs for NAS 5G and then use the asn1-compiler to build a Rust datamodel that can encode/decode NAS 5G messages?
If no, is there any alternative to do such things?

Thanks!!

**Comment by gabhijit** [comment]
@linouxis9 : Nope - Hampi is not currently (and probably ever will be) supporting NAS 5G encoding decoding. Though I started with a bit of that in another repository [here](https://github.com/gabhijit/taxila/tree/main/nas). Though at the moment it's very basic and can't do much. You are welcome to extend that implementation.

**Comment by linouxis9** [comment]
Thank you for your fast answer @gabhijit, and the link to your other project! 
I've been working on translating free5gc's Go NAS 5G Data Models generator in Rust (and obviously to output Rust) https://github.com/free5gc/nas/tree/main/internal/tools/generator, I'll be sure to keep you updated if I'm able to achieve something acceptable.
Thanks!

**Comment by linouxis9** [comment]
Hey @gabhijit:!

I hope you are doing well. I've just released my very first version of a NAS encoder/decoder library in Rust, feel free to check it out :-)

[oxirush-nas](https://github.com/linouxis9/oxirush-nas)!

Thanks a lot for the inspiration.

Cheers,
Valentin
